// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: proto/stanc.proto
#ifndef GRPC_proto_2fstanc_2eproto__INCLUDED
#define GRPC_proto_2fstanc_2eproto__INCLUDED

#include "proto/stanc.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class CompileService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CompileProgram(::grpc::ClientContext* context, const ::StanCompileRequest& request, ::StanCompileResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::StanCompileResponse>> AsyncCompileProgram(::grpc::ClientContext* context, const ::StanCompileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::StanCompileResponse>>(AsyncCompileProgramRaw(context, request, cq));
    }
    virtual ::grpc::Status CompileCheck(::grpc::ClientContext* context, const ::StanCompileCheck& request, ::StanCompileResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::StanCompileResponse>> AsyncCompileCheck(::grpc::ClientContext* context, const ::StanCompileCheck& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::StanCompileResponse>>(AsyncCompileCheckRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::StanCompileResponse>* AsyncCompileProgramRaw(::grpc::ClientContext* context, const ::StanCompileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::StanCompileResponse>* AsyncCompileCheckRaw(::grpc::ClientContext* context, const ::StanCompileCheck& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status CompileProgram(::grpc::ClientContext* context, const ::StanCompileRequest& request, ::StanCompileResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::StanCompileResponse>> AsyncCompileProgram(::grpc::ClientContext* context, const ::StanCompileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::StanCompileResponse>>(AsyncCompileProgramRaw(context, request, cq));
    }
    ::grpc::Status CompileCheck(::grpc::ClientContext* context, const ::StanCompileCheck& request, ::StanCompileResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::StanCompileResponse>> AsyncCompileCheck(::grpc::ClientContext* context, const ::StanCompileCheck& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::StanCompileResponse>>(AsyncCompileCheckRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::StanCompileResponse>* AsyncCompileProgramRaw(::grpc::ClientContext* context, const ::StanCompileRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::StanCompileResponse>* AsyncCompileCheckRaw(::grpc::ClientContext* context, const ::StanCompileCheck& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_CompileProgram_;
    const ::grpc::RpcMethod rpcmethod_CompileCheck_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CompileProgram(::grpc::ServerContext* context, const ::StanCompileRequest* request, ::StanCompileResponse* response);
    virtual ::grpc::Status CompileCheck(::grpc::ServerContext* context, const ::StanCompileCheck* request, ::StanCompileResponse* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    std::unique_ptr< ::grpc::RpcService> service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestCompileProgram(::grpc::ServerContext* context, ::StanCompileRequest* request, ::grpc::ServerAsyncResponseWriter< ::StanCompileResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestCompileCheck(::grpc::ServerContext* context, ::StanCompileCheck* request, ::grpc::ServerAsyncResponseWriter< ::StanCompileResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};


#endif  // GRPC_proto_2fstanc_2eproto__INCLUDED
