// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/stanc.proto

#ifndef PROTOBUF_proto_2fstanc_2eproto__INCLUDED
#define PROTOBUF_proto_2fstanc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace stan {
namespace serve {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fstanc_2eproto();
void protobuf_AssignDesc_proto_2fstanc_2eproto();
void protobuf_ShutdownFile_proto_2fstanc_2eproto();

class StanCompileRequest;
class StanCompileResponse;
class StanMessage;
class StanVersion;

enum StanMessage_Type {
  StanMessage_Type_UNKNOWN = 0,
  StanMessage_Type_EMPTY = 1,
  StanMessage_Type_COMPILE_REQUEST = 2,
  StanMessage_Type_COMPILE_RESPONSE = 3,
  StanMessage_Type_COMPILE_CHECK = 4,
  StanMessage_Type_StanMessage_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  StanMessage_Type_StanMessage_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool StanMessage_Type_IsValid(int value);
const StanMessage_Type StanMessage_Type_Type_MIN = StanMessage_Type_UNKNOWN;
const StanMessage_Type StanMessage_Type_Type_MAX = StanMessage_Type_COMPILE_CHECK;
const int StanMessage_Type_Type_ARRAYSIZE = StanMessage_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* StanMessage_Type_descriptor();
inline const ::std::string& StanMessage_Type_Name(StanMessage_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    StanMessage_Type_descriptor(), value);
}
inline bool StanMessage_Type_Parse(
    const ::std::string& name, StanMessage_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StanMessage_Type>(
    StanMessage_Type_descriptor(), name, value);
}
enum StanCompileResponse_State {
  StanCompileResponse_State_UNKNOWN = 0,
  StanCompileResponse_State_INCOMPLETE = 1,
  StanCompileResponse_State_SUCCESS = 2,
  StanCompileResponse_State_WARN = 3,
  StanCompileResponse_State_ERROR = 4,
  StanCompileResponse_State_StanCompileResponse_State_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  StanCompileResponse_State_StanCompileResponse_State_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool StanCompileResponse_State_IsValid(int value);
const StanCompileResponse_State StanCompileResponse_State_State_MIN = StanCompileResponse_State_UNKNOWN;
const StanCompileResponse_State StanCompileResponse_State_State_MAX = StanCompileResponse_State_ERROR;
const int StanCompileResponse_State_State_ARRAYSIZE = StanCompileResponse_State_State_MAX + 1;

const ::google::protobuf::EnumDescriptor* StanCompileResponse_State_descriptor();
inline const ::std::string& StanCompileResponse_State_Name(StanCompileResponse_State value) {
  return ::google::protobuf::internal::NameOfEnum(
    StanCompileResponse_State_descriptor(), value);
}
inline bool StanCompileResponse_State_Parse(
    const ::std::string& name, StanCompileResponse_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StanCompileResponse_State>(
    StanCompileResponse_State_descriptor(), name, value);
}
// ===================================================================

class StanMessage : public ::google::protobuf::Message {
 public:
  StanMessage();
  virtual ~StanMessage();

  StanMessage(const StanMessage& from);

  inline StanMessage& operator=(const StanMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StanMessage& default_instance();

  void Swap(StanMessage* other);

  // implements Message ----------------------------------------------

  inline StanMessage* New() const { return New(NULL); }

  StanMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StanMessage& from);
  void MergeFrom(const StanMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StanMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef StanMessage_Type Type;
  static const Type UNKNOWN = StanMessage_Type_UNKNOWN;
  static const Type EMPTY = StanMessage_Type_EMPTY;
  static const Type COMPILE_REQUEST = StanMessage_Type_COMPILE_REQUEST;
  static const Type COMPILE_RESPONSE = StanMessage_Type_COMPILE_RESPONSE;
  static const Type COMPILE_CHECK = StanMessage_Type_COMPILE_CHECK;
  static inline bool Type_IsValid(int value) {
    return StanMessage_Type_IsValid(value);
  }
  static const Type Type_MIN =
    StanMessage_Type_Type_MIN;
  static const Type Type_MAX =
    StanMessage_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    StanMessage_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return StanMessage_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return StanMessage_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return StanMessage_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .stan.serve.StanMessage.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::stan::serve::StanMessage_Type type() const;
  void set_type(::stan::serve::StanMessage_Type value);

  // optional .stan.serve.StanCompileRequest stan_compile_request = 2;
  bool has_stan_compile_request() const;
  void clear_stan_compile_request();
  static const int kStanCompileRequestFieldNumber = 2;
  const ::stan::serve::StanCompileRequest& stan_compile_request() const;
  ::stan::serve::StanCompileRequest* mutable_stan_compile_request();
  ::stan::serve::StanCompileRequest* release_stan_compile_request();
  void set_allocated_stan_compile_request(::stan::serve::StanCompileRequest* stan_compile_request);

  // optional .stan.serve.StanCompileResponse stan_compile_response = 3;
  bool has_stan_compile_response() const;
  void clear_stan_compile_response();
  static const int kStanCompileResponseFieldNumber = 3;
  const ::stan::serve::StanCompileResponse& stan_compile_response() const;
  ::stan::serve::StanCompileResponse* mutable_stan_compile_response();
  ::stan::serve::StanCompileResponse* release_stan_compile_response();
  void set_allocated_stan_compile_response(::stan::serve::StanCompileResponse* stan_compile_response);

  // @@protoc_insertion_point(class_scope:stan.serve.StanMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::stan::serve::StanCompileRequest* stan_compile_request_;
  ::stan::serve::StanCompileResponse* stan_compile_response_;
  int type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fstanc_2eproto();
  friend void protobuf_AssignDesc_proto_2fstanc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fstanc_2eproto();

  void InitAsDefaultInstance();
  static StanMessage* default_instance_;
};
// -------------------------------------------------------------------

class StanVersion : public ::google::protobuf::Message {
 public:
  StanVersion();
  virtual ~StanVersion();

  StanVersion(const StanVersion& from);

  inline StanVersion& operator=(const StanVersion& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StanVersion& default_instance();

  void Swap(StanVersion* other);

  // implements Message ----------------------------------------------

  inline StanVersion* New() const { return New(NULL); }

  StanVersion* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StanVersion& from);
  void MergeFrom(const StanVersion& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StanVersion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string version = 1;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // optional string stan_math_hash = 2;
  void clear_stan_math_hash();
  static const int kStanMathHashFieldNumber = 2;
  const ::std::string& stan_math_hash() const;
  void set_stan_math_hash(const ::std::string& value);
  void set_stan_math_hash(const char* value);
  void set_stan_math_hash(const char* value, size_t size);
  ::std::string* mutable_stan_math_hash();
  ::std::string* release_stan_math_hash();
  void set_allocated_stan_math_hash(::std::string* stan_math_hash);

  // optional string stan_stan_hash = 3;
  void clear_stan_stan_hash();
  static const int kStanStanHashFieldNumber = 3;
  const ::std::string& stan_stan_hash() const;
  void set_stan_stan_hash(const ::std::string& value);
  void set_stan_stan_hash(const char* value);
  void set_stan_stan_hash(const char* value, size_t size);
  ::std::string* mutable_stan_stan_hash();
  ::std::string* release_stan_stan_hash();
  void set_allocated_stan_stan_hash(::std::string* stan_stan_hash);

  // @@protoc_insertion_point(class_scope:stan.serve.StanVersion)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr stan_math_hash_;
  ::google::protobuf::internal::ArenaStringPtr stan_stan_hash_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fstanc_2eproto();
  friend void protobuf_AssignDesc_proto_2fstanc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fstanc_2eproto();

  void InitAsDefaultInstance();
  static StanVersion* default_instance_;
};
// -------------------------------------------------------------------

class StanCompileRequest : public ::google::protobuf::Message {
 public:
  StanCompileRequest();
  virtual ~StanCompileRequest();

  StanCompileRequest(const StanCompileRequest& from);

  inline StanCompileRequest& operator=(const StanCompileRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StanCompileRequest& default_instance();

  void Swap(StanCompileRequest* other);

  // implements Message ----------------------------------------------

  inline StanCompileRequest* New() const { return New(NULL); }

  StanCompileRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StanCompileRequest& from);
  void MergeFrom(const StanCompileRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StanCompileRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string model_name = 1;
  void clear_model_name();
  static const int kModelNameFieldNumber = 1;
  const ::std::string& model_name() const;
  void set_model_name(const ::std::string& value);
  void set_model_name(const char* value);
  void set_model_name(const char* value, size_t size);
  ::std::string* mutable_model_name();
  ::std::string* release_model_name();
  void set_allocated_model_name(::std::string* model_name);

  // optional string model_code = 2;
  void clear_model_code();
  static const int kModelCodeFieldNumber = 2;
  const ::std::string& model_code() const;
  void set_model_code(const ::std::string& value);
  void set_model_code(const char* value);
  void set_model_code(const char* value, size_t size);
  ::std::string* mutable_model_code();
  ::std::string* release_model_code();
  void set_allocated_model_code(::std::string* model_code);

  // optional string model_file_name = 3;
  void clear_model_file_name();
  static const int kModelFileNameFieldNumber = 3;
  const ::std::string& model_file_name() const;
  void set_model_file_name(const ::std::string& value);
  void set_model_file_name(const char* value);
  void set_model_file_name(const char* value, size_t size);
  ::std::string* mutable_model_file_name();
  ::std::string* release_model_file_name();
  void set_allocated_model_file_name(::std::string* model_file_name);

  // @@protoc_insertion_point(class_scope:stan.serve.StanCompileRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr model_name_;
  ::google::protobuf::internal::ArenaStringPtr model_code_;
  ::google::protobuf::internal::ArenaStringPtr model_file_name_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fstanc_2eproto();
  friend void protobuf_AssignDesc_proto_2fstanc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fstanc_2eproto();

  void InitAsDefaultInstance();
  static StanCompileRequest* default_instance_;
};
// -------------------------------------------------------------------

class StanCompileResponse : public ::google::protobuf::Message {
 public:
  StanCompileResponse();
  virtual ~StanCompileResponse();

  StanCompileResponse(const StanCompileResponse& from);

  inline StanCompileResponse& operator=(const StanCompileResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StanCompileResponse& default_instance();

  void Swap(StanCompileResponse* other);

  // implements Message ----------------------------------------------

  inline StanCompileResponse* New() const { return New(NULL); }

  StanCompileResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StanCompileResponse& from);
  void MergeFrom(const StanCompileResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StanCompileResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef StanCompileResponse_State State;
  static const State UNKNOWN = StanCompileResponse_State_UNKNOWN;
  static const State INCOMPLETE = StanCompileResponse_State_INCOMPLETE;
  static const State SUCCESS = StanCompileResponse_State_SUCCESS;
  static const State WARN = StanCompileResponse_State_WARN;
  static const State ERROR = StanCompileResponse_State_ERROR;
  static inline bool State_IsValid(int value) {
    return StanCompileResponse_State_IsValid(value);
  }
  static const State State_MIN =
    StanCompileResponse_State_State_MIN;
  static const State State_MAX =
    StanCompileResponse_State_State_MAX;
  static const int State_ARRAYSIZE =
    StanCompileResponse_State_State_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  State_descriptor() {
    return StanCompileResponse_State_descriptor();
  }
  static inline const ::std::string& State_Name(State value) {
    return StanCompileResponse_State_Name(value);
  }
  static inline bool State_Parse(const ::std::string& name,
      State* value) {
    return StanCompileResponse_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .stan.serve.StanCompileResponse.State state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::stan::serve::StanCompileResponse_State state() const;
  void set_state(::stan::serve::StanCompileResponse_State value);

  // optional string cpp_code = 3;
  void clear_cpp_code();
  static const int kCppCodeFieldNumber = 3;
  const ::std::string& cpp_code() const;
  void set_cpp_code(const ::std::string& value);
  void set_cpp_code(const char* value);
  void set_cpp_code(const char* value, size_t size);
  ::std::string* mutable_cpp_code();
  ::std::string* release_cpp_code();
  void set_allocated_cpp_code(::std::string* cpp_code);

  // optional string messages = 4;
  void clear_messages();
  static const int kMessagesFieldNumber = 4;
  const ::std::string& messages() const;
  void set_messages(const ::std::string& value);
  void set_messages(const char* value);
  void set_messages(const char* value, size_t size);
  ::std::string* mutable_messages();
  ::std::string* release_messages();
  void set_allocated_messages(::std::string* messages);

  // @@protoc_insertion_point(class_scope:stan.serve.StanCompileResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr cpp_code_;
  ::google::protobuf::internal::ArenaStringPtr messages_;
  int state_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fstanc_2eproto();
  friend void protobuf_AssignDesc_proto_2fstanc_2eproto();
  friend void protobuf_ShutdownFile_proto_2fstanc_2eproto();

  void InitAsDefaultInstance();
  static StanCompileResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// StanMessage

// optional .stan.serve.StanMessage.Type type = 1;
inline void StanMessage::clear_type() {
  type_ = 0;
}
inline ::stan::serve::StanMessage_Type StanMessage::type() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanMessage.type)
  return static_cast< ::stan::serve::StanMessage_Type >(type_);
}
inline void StanMessage::set_type(::stan::serve::StanMessage_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:stan.serve.StanMessage.type)
}

// optional .stan.serve.StanCompileRequest stan_compile_request = 2;
inline bool StanMessage::has_stan_compile_request() const {
  return !_is_default_instance_ && stan_compile_request_ != NULL;
}
inline void StanMessage::clear_stan_compile_request() {
  if (GetArenaNoVirtual() == NULL && stan_compile_request_ != NULL) delete stan_compile_request_;
  stan_compile_request_ = NULL;
}
inline const ::stan::serve::StanCompileRequest& StanMessage::stan_compile_request() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanMessage.stan_compile_request)
  return stan_compile_request_ != NULL ? *stan_compile_request_ : *default_instance_->stan_compile_request_;
}
inline ::stan::serve::StanCompileRequest* StanMessage::mutable_stan_compile_request() {
  
  if (stan_compile_request_ == NULL) {
    stan_compile_request_ = new ::stan::serve::StanCompileRequest;
  }
  // @@protoc_insertion_point(field_mutable:stan.serve.StanMessage.stan_compile_request)
  return stan_compile_request_;
}
inline ::stan::serve::StanCompileRequest* StanMessage::release_stan_compile_request() {
  
  ::stan::serve::StanCompileRequest* temp = stan_compile_request_;
  stan_compile_request_ = NULL;
  return temp;
}
inline void StanMessage::set_allocated_stan_compile_request(::stan::serve::StanCompileRequest* stan_compile_request) {
  delete stan_compile_request_;
  stan_compile_request_ = stan_compile_request;
  if (stan_compile_request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanMessage.stan_compile_request)
}

// optional .stan.serve.StanCompileResponse stan_compile_response = 3;
inline bool StanMessage::has_stan_compile_response() const {
  return !_is_default_instance_ && stan_compile_response_ != NULL;
}
inline void StanMessage::clear_stan_compile_response() {
  if (GetArenaNoVirtual() == NULL && stan_compile_response_ != NULL) delete stan_compile_response_;
  stan_compile_response_ = NULL;
}
inline const ::stan::serve::StanCompileResponse& StanMessage::stan_compile_response() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanMessage.stan_compile_response)
  return stan_compile_response_ != NULL ? *stan_compile_response_ : *default_instance_->stan_compile_response_;
}
inline ::stan::serve::StanCompileResponse* StanMessage::mutable_stan_compile_response() {
  
  if (stan_compile_response_ == NULL) {
    stan_compile_response_ = new ::stan::serve::StanCompileResponse;
  }
  // @@protoc_insertion_point(field_mutable:stan.serve.StanMessage.stan_compile_response)
  return stan_compile_response_;
}
inline ::stan::serve::StanCompileResponse* StanMessage::release_stan_compile_response() {
  
  ::stan::serve::StanCompileResponse* temp = stan_compile_response_;
  stan_compile_response_ = NULL;
  return temp;
}
inline void StanMessage::set_allocated_stan_compile_response(::stan::serve::StanCompileResponse* stan_compile_response) {
  delete stan_compile_response_;
  stan_compile_response_ = stan_compile_response;
  if (stan_compile_response) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanMessage.stan_compile_response)
}

// -------------------------------------------------------------------

// StanVersion

// optional string version = 1;
inline void StanVersion::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanVersion::version() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanVersion.version)
  return version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanVersion::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanVersion.version)
}
inline void StanVersion::set_version(const char* value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanVersion.version)
}
inline void StanVersion::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanVersion.version)
}
inline ::std::string* StanVersion::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanVersion.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanVersion::release_version() {
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanVersion::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanVersion.version)
}

// optional string stan_math_hash = 2;
inline void StanVersion::clear_stan_math_hash() {
  stan_math_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanVersion::stan_math_hash() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanVersion.stan_math_hash)
  return stan_math_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanVersion::set_stan_math_hash(const ::std::string& value) {
  
  stan_math_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanVersion.stan_math_hash)
}
inline void StanVersion::set_stan_math_hash(const char* value) {
  
  stan_math_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanVersion.stan_math_hash)
}
inline void StanVersion::set_stan_math_hash(const char* value, size_t size) {
  
  stan_math_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanVersion.stan_math_hash)
}
inline ::std::string* StanVersion::mutable_stan_math_hash() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanVersion.stan_math_hash)
  return stan_math_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanVersion::release_stan_math_hash() {
  
  return stan_math_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanVersion::set_allocated_stan_math_hash(::std::string* stan_math_hash) {
  if (stan_math_hash != NULL) {
    
  } else {
    
  }
  stan_math_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), stan_math_hash);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanVersion.stan_math_hash)
}

// optional string stan_stan_hash = 3;
inline void StanVersion::clear_stan_stan_hash() {
  stan_stan_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanVersion::stan_stan_hash() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanVersion.stan_stan_hash)
  return stan_stan_hash_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanVersion::set_stan_stan_hash(const ::std::string& value) {
  
  stan_stan_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanVersion.stan_stan_hash)
}
inline void StanVersion::set_stan_stan_hash(const char* value) {
  
  stan_stan_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanVersion.stan_stan_hash)
}
inline void StanVersion::set_stan_stan_hash(const char* value, size_t size) {
  
  stan_stan_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanVersion.stan_stan_hash)
}
inline ::std::string* StanVersion::mutable_stan_stan_hash() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanVersion.stan_stan_hash)
  return stan_stan_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanVersion::release_stan_stan_hash() {
  
  return stan_stan_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanVersion::set_allocated_stan_stan_hash(::std::string* stan_stan_hash) {
  if (stan_stan_hash != NULL) {
    
  } else {
    
  }
  stan_stan_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), stan_stan_hash);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanVersion.stan_stan_hash)
}

// -------------------------------------------------------------------

// StanCompileRequest

// optional string model_name = 1;
inline void StanCompileRequest::clear_model_name() {
  model_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanCompileRequest::model_name() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanCompileRequest.model_name)
  return model_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileRequest::set_model_name(const ::std::string& value) {
  
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanCompileRequest.model_name)
}
inline void StanCompileRequest::set_model_name(const char* value) {
  
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanCompileRequest.model_name)
}
inline void StanCompileRequest::set_model_name(const char* value, size_t size) {
  
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanCompileRequest.model_name)
}
inline ::std::string* StanCompileRequest::mutable_model_name() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanCompileRequest.model_name)
  return model_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanCompileRequest::release_model_name() {
  
  return model_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileRequest::set_allocated_model_name(::std::string* model_name) {
  if (model_name != NULL) {
    
  } else {
    
  }
  model_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_name);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanCompileRequest.model_name)
}

// optional string model_code = 2;
inline void StanCompileRequest::clear_model_code() {
  model_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanCompileRequest::model_code() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanCompileRequest.model_code)
  return model_code_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileRequest::set_model_code(const ::std::string& value) {
  
  model_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanCompileRequest.model_code)
}
inline void StanCompileRequest::set_model_code(const char* value) {
  
  model_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanCompileRequest.model_code)
}
inline void StanCompileRequest::set_model_code(const char* value, size_t size) {
  
  model_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanCompileRequest.model_code)
}
inline ::std::string* StanCompileRequest::mutable_model_code() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanCompileRequest.model_code)
  return model_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanCompileRequest::release_model_code() {
  
  return model_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileRequest::set_allocated_model_code(::std::string* model_code) {
  if (model_code != NULL) {
    
  } else {
    
  }
  model_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_code);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanCompileRequest.model_code)
}

// optional string model_file_name = 3;
inline void StanCompileRequest::clear_model_file_name() {
  model_file_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanCompileRequest::model_file_name() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanCompileRequest.model_file_name)
  return model_file_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileRequest::set_model_file_name(const ::std::string& value) {
  
  model_file_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanCompileRequest.model_file_name)
}
inline void StanCompileRequest::set_model_file_name(const char* value) {
  
  model_file_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanCompileRequest.model_file_name)
}
inline void StanCompileRequest::set_model_file_name(const char* value, size_t size) {
  
  model_file_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanCompileRequest.model_file_name)
}
inline ::std::string* StanCompileRequest::mutable_model_file_name() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanCompileRequest.model_file_name)
  return model_file_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanCompileRequest::release_model_file_name() {
  
  return model_file_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileRequest::set_allocated_model_file_name(::std::string* model_file_name) {
  if (model_file_name != NULL) {
    
  } else {
    
  }
  model_file_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_file_name);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanCompileRequest.model_file_name)
}

// -------------------------------------------------------------------

// StanCompileResponse

// optional .stan.serve.StanCompileResponse.State state = 2;
inline void StanCompileResponse::clear_state() {
  state_ = 0;
}
inline ::stan::serve::StanCompileResponse_State StanCompileResponse::state() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanCompileResponse.state)
  return static_cast< ::stan::serve::StanCompileResponse_State >(state_);
}
inline void StanCompileResponse::set_state(::stan::serve::StanCompileResponse_State value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:stan.serve.StanCompileResponse.state)
}

// optional string cpp_code = 3;
inline void StanCompileResponse::clear_cpp_code() {
  cpp_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanCompileResponse::cpp_code() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanCompileResponse.cpp_code)
  return cpp_code_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileResponse::set_cpp_code(const ::std::string& value) {
  
  cpp_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanCompileResponse.cpp_code)
}
inline void StanCompileResponse::set_cpp_code(const char* value) {
  
  cpp_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanCompileResponse.cpp_code)
}
inline void StanCompileResponse::set_cpp_code(const char* value, size_t size) {
  
  cpp_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanCompileResponse.cpp_code)
}
inline ::std::string* StanCompileResponse::mutable_cpp_code() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanCompileResponse.cpp_code)
  return cpp_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanCompileResponse::release_cpp_code() {
  
  return cpp_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileResponse::set_allocated_cpp_code(::std::string* cpp_code) {
  if (cpp_code != NULL) {
    
  } else {
    
  }
  cpp_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cpp_code);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanCompileResponse.cpp_code)
}

// optional string messages = 4;
inline void StanCompileResponse::clear_messages() {
  messages_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StanCompileResponse::messages() const {
  // @@protoc_insertion_point(field_get:stan.serve.StanCompileResponse.messages)
  return messages_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileResponse::set_messages(const ::std::string& value) {
  
  messages_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:stan.serve.StanCompileResponse.messages)
}
inline void StanCompileResponse::set_messages(const char* value) {
  
  messages_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:stan.serve.StanCompileResponse.messages)
}
inline void StanCompileResponse::set_messages(const char* value, size_t size) {
  
  messages_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:stan.serve.StanCompileResponse.messages)
}
inline ::std::string* StanCompileResponse::mutable_messages() {
  
  // @@protoc_insertion_point(field_mutable:stan.serve.StanCompileResponse.messages)
  return messages_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StanCompileResponse::release_messages() {
  
  return messages_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StanCompileResponse::set_allocated_messages(::std::string* messages) {
  if (messages != NULL) {
    
  } else {
    
  }
  messages_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), messages);
  // @@protoc_insertion_point(field_set_allocated:stan.serve.StanCompileResponse.messages)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace serve
}  // namespace stan

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::stan::serve::StanMessage_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::stan::serve::StanMessage_Type>() {
  return ::stan::serve::StanMessage_Type_descriptor();
}
template <> struct is_proto_enum< ::stan::serve::StanCompileResponse_State> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::stan::serve::StanCompileResponse_State>() {
  return ::stan::serve::StanCompileResponse_State_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fstanc_2eproto__INCLUDED
